### ISSUE TITLE
compare_which_columns_differ: does not exist

### ISSUE THREAD

**Issue by mtsadler-branch** [dbt-labs/dbt-audit-helper#106]
### Describe the bug
The `compare_which_columns_differ` macro doesnt exist.

However, there's a `compare_which_relation_columns_differ` macro, but it doesn't accept `exclude_columns`.

### Screenshots and log output
https://github.com/dbt-labs/dbt-audit-helper/blob/main/macros/compare_which_relation_columns_differ.sql

### System information
**The contents of your `packages.yml` file:**

  - package: dbt-labs/audit_helper
    version: 0.12.0

**Which database are you using dbt with?**
- [x] snowflake

**Comment by joellabes** [comment]
@mtsadler-branch sorry for the delay - just merged an updated readme which includes guidance on how to get exclude_columns behaviour with a dbt_utils macro: https://github.com/dbt-labs/dbt-audit-helper?tab=readme-ov-file#compare_which_relation_columns_differ-source
