### ISSUE TITLE
'dbt.context.macros.MacroNamespace object' has no attribute 'compare_which_columns_differ'

### ISSUE THREAD

**Issue by ryantimjohn** [dbt-labs/dbt-audit-helper#113]
### Describe the bug
Compare which columns differ doesn't seem to exist, should be removed from docs here:
https://github.com/dbt-labs/dbt-audit-helper?tab=readme-ov-file#usage-5

### Steps to reproduce
ran this code:
```
{% set old_relation = api.Relation.create(database='x',schema='x, identifier='mart_paidmedia_daily_revenue_performance') %}
{% set dbt_relation = ref('mart_paidmedia_daily_revenue_performance') %}

{{ audit_helper.compare_which_columns_differ(
    a_relation = old_relation,
    b_relation = dbt_relation,
    primary_key = "message_id"
) }}
```

**Comment by joellabes** [comment]
@ryantimjohn I don't see `compare_which_columns_differ` on the readme page, just `compare_which_query_columns_differ` and `compare_which_relation_columns_differ` - can you let me know where you're still seeing it in the docs?

**Comment by ryantimjohn** [comment]
@joellabes it's been updated since then and `compare_which_columns_differ` was removed so we can close this out!

**Comment by ryantimjohn** [comment]
@joellabes This was the commit where that was removed (happened two weeks after me opening the issue):
https://github.com/dbt-labs/dbt-audit-helper/commit/2462be748c6f1d5fccb45c011c21b8c9f479bde6

**Comment by joellabes** [comment]
Ah my bad thank you!
