### ISSUE TITLE
Easier toggle between summary and diff when comparing relations and queries

### ISSUE THREAD

**Issue by PhilipCorr** [dbt-labs/dbt-audit-helper#33]
### Describe the feature
I've found the compare_queries and compare_relations very useful. It would be great to add an optional parameter when calling the compare_queries and compare_relations macros which would allow for an easy switch between the summary output and the full diff output so that we don't need to manually switch by commenting/uncommenting.

It's a small change and I would be happy to contribute it myself if that's something that is possible?

### Who will this benefit?
Anyone who sees that the two relations aren't exactly the same and wants to see the rows that differ between the two relations.

### Are you interested in contributing this feature?
Yes. My suggested change is small. I'm thinking something like this (where diff is the optional parameter and defaults to false to maintain backwards compatability):

```
{% if diff %}

compared_queries as (
    select
        *
    from all_records
    where not (in_a and in_b)
    order by {{ primary_key ~ ", " if primary_key is not none }} in_a desc, in_b desc
)

{% else %}

summary_stats as (
    select
        in_a,
        in_b,
        count(*) as count
    from all_records
    group by 1, 2
),

compared_queries as (
    select
        *,
        round(100.0 * count / sum(count) over (), 2) as percent_of_total
    from summary_stats
    order by in_a desc, in_b desc
)

{% endif %}
```

**Comment by christineberger** [comment]
@PhilipCorr I was looking for an open request similar to this! ➕ - I use compare_relations heavily and was thinking of a similar request. I'm going to throw this under yours since it seems to be related!

Example Usage:
```jinja
{% set old_etl_relation=ref('original_model') -%}
{% set dbt_relation=ref('new_model') %}

{{ audit_helper.compare_relations(
    a_relation=old_etl_relation,
    b_relation=dbt_relation,
    primary_key="primary_id"
    summary_mode=false               # Optional, setting this to false would give you the row-by-row comparison
) }}
```

Underlying code:
```sql
{% macro default__compare_queries(a_query, b_query, primary_key=None, summary_mode=true) %}

with a as (

    {{ a_query }}

),

b as (

    {{ b_query }}

),

a_intersect_b as (

    select * from a
    {{ dbt_utils.intersect() }}
    select * from b

),

a_except_b as (

    select * from a
    {{ dbt_utils.except() }}
    select * from b

),

b_except_a as (

    select * from b
    {{ dbt_utils.except() }}
    select * from a

),

all_records as (

    select
        *,
        true as in_a,
        true as in_b
    from a_intersect_b

    union all

    select
        *,
        true as in_a,
        false as in_b
    from a_except_b

    union all

    select
        *,
        false as in_a,
        true as in_b
    from b_except_a

),

{%- if summary_mode == true %}

summary_stats as (
    select
        in_a,
        in_b,
        count(*) as count
    from all_records
    group by 1, 2
),

final as (

  select
      *,
      round(100.0 * count / sum(count) over (), 2) as percent_of_total
  from summary_stats
  order by in_a desc, in_b desc

)

{%- else %}

final as (
  select * from all_records
  where not (in_a and in_b)
  order by {{ primary_key ~ ", " if primary_key is not none }} in_a desc, in_b desc
)

{%- endif %}

select * from final

{% endmacro %}
```

**Comment by PhilipCorr** [comment]
Hi @christineberger, it's been quite a while since I was looking at this and I never managed to get much more traction on it than what you see here. Feel free to take this and run with it however suits you! I won't have the time to do much with it myself soon, unfortunately.

**Comment by joellabes** [comment]
YES I am so into this @PhilipCorr and @christineberger - checking out the PR now!
