### ISSUE TITLE
dbt_utils: Could not find a satisfactory version from options: ['=0.7.0', '>=0.6.0', '<0.7.0', '>=0.6.0', '<0.7.0', '>=0.4.0', '<0.7.0']

### ISSUE THREAD

**Issue by asmurthy** [dbt-labs/dbt-audit-helper#38]
### Describe the bug
I have dbt version 0.20.0
I am trying to run 'dbt deps' in install dbt utils
I see this error message:
fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.7.0', '>=0.6.0', '<0.7.0', '>=0.6.0', '<0.7.0', '>=0.4.0', '<0.7.0']

**Comment by jtcohen6** [comment]
Hi @asmurthy, could you provide the full contents of your `packages.yml`? It sounds like you have some dependency conflicts.

The latest version of this package (v0.4.0) is compatible with dbt v0.20 and dbt-utils v0.7.

**Comment by erika-e** [comment]
@jtcohen6 the latest version on the hub is [0.3.0](https://hub.getdbt.com/fishtown-analytics/audit_helper/latest/)

**Comment by jtcohen6** [comment]
@erika-e Ah, sorry for the confusion. Going forward, we'll be serving the latest versions of our packages in the `dbt-labs` namespace: https://hub.getdbt.com/dbt-labs/audit_helper/latest/. The `fishtown-analytics` versions are there for backwards compatibility.

More details in discourse: https://discourse.getdbt.com/t/packages-dbt-labs-in-the-dbt-hub/2711/4

**Comment by erika-e** [comment]
🤦‍♀️  I just popped the hub in google and didn't even think of that. Thanks for clarifying and for the speedy response!

**Comment by asmurthy** [comment]
@jtcohen6 - I think it was related to the version of dbt. It looks OK now. Thanks
