### ISSUE TITLE
add column name to `compare_column_values` output

### ISSUE THREAD

**Issue by leoebfolsom** [dbt-labs/dbt-audit-helper#46]
### Describe the feature
I would like the `compare_column_values` macro to include a column called `column_name`. This would make it easier (possible?) to incorporate this package into a dbt test suite that tested all the columns in a model (or multiple models). I brought this up in Slack--[here's a link](https://getdbt.slack.com/archives/CU4MRJ7QB/p1656528686395859) in case there's any discussion).

### Describe alternatives you've considered
- Paid tools exist.
- Not sure there is an alternative other than testing every column individually.

### Additional context
I am building this for our Snowflake warehouse, but I think it would work across warehouses.

### Who will this benefit?
This is for AEs and other data stakeholders who want to run a rigorous test suite that detects data changes when a PR is submitted (or, more generally, data changes between different versions of code).

### Are you interested in contributing this feature?
Yes--I'm currently working on a branch on a fork and will open a PR shortly (happy to take direction/guidance and adjust accordingly).

**Comment by joellabes** [comment]
Resolved by #47
