### ISSUE TITLE
compare_relations adapter.get_relation doesn't work as in the README

### ISSUE THREAD

**Issue by christineberger** [dbt-labs/dbt-audit-helper#82]
### Describe the bug
The compare_relations macro seems to have an issue with the adapter.get_relation value on the get_filtered_columns_in_relation operation. It seems to work with an {% if execute %} wrapper, though.

### Steps to reproduce

Copy the code from the README for compare_relations, then use it as-is, swapping the adapter.get_relations call to an accessible table. Try to run the macro - you will get an error with an empty value.

### Expected results
A summarized comparison between the two datasets. Using Benoit's suggestion from an internal channel, the macro works fine like this:
```
{% set dbt_relation=ref('orders') %}

{% if execute %}
    {%- set old_etl_relation = adapter.get_relation(
        database="ANALYTICS",
        schema="DBT_COHMS",
        identifier="FCT_ORDERS") -%}

    {{ audit_helper.compare_relations(
        a_relation=old_etl_relation,
        b_relation=dbt_relation,
        primary_key="order_id"
    ) }}
{% endif %}
```

### Actual results
With the snippet in the README:
![Screenshot 2023-09-12 at 6 01 17 PM](https://github.com/dbt-labs/dbt-audit-helper/assets/60892553/cf438758-08ea-47a0-9392-b46ac4f7e87d)

Benoit's version:
![Screenshot 2023-09-12 at 6 06 58 PM](https://github.com/dbt-labs/dbt-audit-helper/assets/60892553/6a520bc7-8533-447d-8530-29a916faf60c)

### System information
**The contents of your `packages.yml` file:**
![Screenshot 2023-09-12 at 6 08 52 PM](https://github.com/dbt-labs/dbt-audit-helper/assets/60892553/eba83a92-5f54-4d8c-bc0a-f89127693c20)

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
1.6.0 - dbt Cloud

**The operating system you're using:**
Mac / Arc Browser

**The output of `python --version`:**
--

### Additional context

It's fine if things now need to be wrapped in `if execute`, but the README should reflect!

### Are you interested in contributing the fix?

Would love to, but don't have time to solution if needed 🥲

**Comment by graciegoheen** [comment]
Just ran into the same issue

**Comment by graciegoheen** [comment]
I'm not sure how you would create an integration test for this, because building a model works fine - it's just the preview that fails.

**Comment by graciegoheen** [comment]
Same issue as reported here https://github.com/dbt-labs/dbt-audit-helper/issues/81

**Comment by joellabes** [comment]
I think that instead of fixing the readme we can/should fix the various macros! 
- compare_relation_columns from grace's example can be fixed by adding an if execute block [in here](https://github.com/dbt-labs/dbt-audit-helper/blob/main/macros/compare_relation_columns.sql#L33-L37) before trying to get the information_schema off the (nonexistent) Relation
- compare_relations from christine's example can be fixed in dbt_utils, by moving the [existing if execute](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/get_filtered_columns_in_relation.sql#L6-L13) check in get_filtered_columns_in_relation to before the is_relation check
