### ISSUE TITLE
dbt is not working

### ISSUE THREAD

**Issue by Jagdish2022** [dbt-labs/dbt-audit-helper#83]
### Describe the feature
When I run the "dbt run" it gives me an error

### Describe alternatives you've considered
I have upgraded all the versions for py, dbt, and sqlserver

below is the error I am getting.

Found 2 models, 4 tests, 0 snapshots, 0 analyses, 161 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

ERROR: Database Error
  ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53); [08001] [Microsoft][ODBC SQL Server Driver]Invalid connection string attribute (0)')

Can anyone please help me with this.

**Comment by graciegoheen** [comment]
This looks like a dbt issue, not an `audit_helper` issue. If you're still running into this, I recommend opening up an issue in the dbt-core repo https://github.com/dbt-labs/dbt-core/issues
