### ISSUE TITLE
compare_all_columns not working on Presto

### ISSUE THREAD

**Issue by evabilski** [dbt-labs/dbt-audit-helper#89]
### Describe the bug
Function compare_all_columns does not work on Presto.

### Steps to reproduce
Create test in Presto environment:

```
{{ audit_helper.compare_all_columns(
    a_relation=ref('test__old'),
    b_relation=ref('test__new'),
    primary_key="col_a"
)}}
```
Models to test (same query for each one):
```
select
 'a' AS col_a,
 'b' AS col_b
```

### Screenshots and log output
```line 29:7: mismatched input 'with'. Expecting: '(', 'SELECT', 'TABLE', 'VALUES'```

### System information

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: Presto)

**The output of `dbt --version`:**
dbt-labs/audit_helper version: 0.9.0

### Additional context
line 45-51, `WITH main as((WITH` double parenthesis followed by WITH does not seem to be allowed.
It works with one parenthesis.

### Are you interested in contributing the fix?
I am going to suggest a PR

**Comment by remilepriol** [comment]
This would  be very helpful for me as well. Meanwhile I am adding it as a project-wise adapter. Thank you for the fix @evabilski  !
